@startmindmap

caption Figure 2.1: Inspecting the Source Code and Parsing using AST
'title Sample Lambda Function

*:<code>
def lambda_handler(event, context):
    result = None
    action = event.get('action')

    if action == 'increment':
        result = event.get('number', 0) + 1
    elif action == 'decrement':
        result = event.get('number', 0) - 1

    response = {'result': result}
    return response
</code>;

** Inspect Source Code
*** AST Parsing
@endmindmap
