@startmindmap

'caption Figure 2.1: Passing each event type of the Source Code through a tracer and log formatter
'title Sample Lambda Function

+[#Orange] Decorator

right side 

++[#lightblue] settrace()
++[#lightblue] tracer
+++[#lightblue] Formatter
+++[#lightblue] Generator
++++[#lightgreen] Log Output

left side 

**[#lightgreen]:<code>
def <function>(*args):
    line...
    line...
    line...
    line...
    exception...
    return <response>
</code>;

@endmindmap
